# Generated by Django 4.2.1 on 2025-10-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExamPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("total_duration_min", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "考试试卷",
                "verbose_name_plural": "考试试卷",
                "db_table": "exam_paper",
            },
        ),
        migrations.CreateModel(
            name="ExamModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_type",
                    models.CharField(
                        choices=[
                            ("LISTENING_MCQ", "听力理解"),
                            ("STORY_RETELL", "故事复述"),
                            ("LISTENING_SA", "听力简答题"),
                            ("ATC_SIM", "模拟通话"),
                            ("OPI", "口语面试"),
                        ],
                        max_length=50,
                    ),
                ),
                ("display_order", models.IntegerField()),
                ("score", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_activate", models.BooleanField(default=True)),
                ("duration", models.BigIntegerField()),
                (
                    "exam_paper",
                    models.ManyToManyField(
                        db_column="exam_paper_id",
                        related_name="exam_paper_module",
                        to="exam.exampaper",
                        verbose_name="关联的考试试卷",
                    ),
                ),
            ],
            options={
                "verbose_name": "考试模块",
                "verbose_name_plural": "考试模块",
                "db_table": "exam_modules",
            },
        ),
    ]
