# Generated by Django 4.2.1 on 2025-10-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exammodule",
            options={"verbose_name": "试题模块", "verbose_name_plural": "试题模块"},
        ),
        migrations.AddField(
            model_name="exammodule",
            name="title",
            field=models.CharField(default="", max_length=200, verbose_name="题目备注"),
        ),
    ]
