# Generated by Django 4.2.1 on 2025-10-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_alter_exammodule_options_exammodule_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exammodule",
            name="duration",
            field=models.BigIntegerField(null=True),
        ),
    ]
