# Generated by Django 4.2.1 on 2025-10-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0003_alter_exammodule_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exammodule",
            name="display_order",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="数字越小越靠前，留空默认为0",
                null=True,
                verbose_name="显示顺序",
            ),
        ),
        migrations.AlterField(
            model_name="exammodule",
            name="duration",
            field=models.BigIntegerField(
                blank=True,
                help_text="考试时长，单位：毫秒（例如：10分钟 = 600000）",
                null=True,
                verbose_name="时长(毫秒)",
            ),
        ),
    ]
