# Generated by Django 4.2.1 on 2025-10-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0004_alter_exammodule_display_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exammodule",
            name="exam_paper",
            field=models.ManyToManyField(
                blank=True,
                db_column="exam_paper_id",
                help_text="可选：将此模块关联到一个或多个试卷",
                related_name="exam_paper_module",
                to="exam.exampaper",
                verbose_name="关联的考试试卷",
            ),
        ),
    ]
