# Generated by Django 4.2.1 on 2025-10-22 06:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        ("account", "0001_initial"),
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="McqChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=1,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="选项标签必须是A、B、C、D中的一个",
                                regex="[ABCD]",
                            )
                        ],
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                ("is_correct", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "选择题选项",
                "verbose_name_plural": "选择题选项",
                "db_table": "mcq_choices",
            },
        ),
        migrations.CreateModel(
            name="McqQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_stem", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audio_asset",
                    models.ForeignKey(
                        db_column="audio_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mcq_questions",
                        to="media.mediaasset",
                        verbose_name="关联音频资源",
                    ),
                ),
                (
                    "exam_module",
                    models.ManyToManyField(
                        blank=True,
                        db_column="module_id",
                        related_name="module_mcq",
                        to="exam.exammodule",
                        verbose_name="关联考试模块",
                    ),
                ),
            ],
            options={
                "verbose_name": "听力选择题",
                "verbose_name_plural": "听力选择题",
                "db_table": "mcq_questions",
            },
        ),
        migrations.CreateModel(
            name="McqResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField(null=True)),
                (
                    "answered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_timeout", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="mcq.mcqquestion",
                        verbose_name="关联题目",
                    ),
                ),
                (
                    "selected_choice",
                    models.ForeignKey(
                        db_column="selected_choice_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="mcq.mcqchoice",
                        verbose_name="被选中的选项",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.wxuser",
                        verbose_name="回答人",
                    ),
                ),
            ],
            options={
                "verbose_name": "选择题作答记录",
                "verbose_name_plural": "选择题作答记录",
                "db_table": "mcq_responses",
            },
        ),
        migrations.AddField(
            model_name="mcqchoice",
            name="question",
            field=models.ForeignKey(
                db_column="question_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="mcq.mcqquestion",
                verbose_name="关联题目",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mcqchoice",
            unique_together={("question", "label")},
        ),
    ]
