# Generated by Django 4.2.1 on 2025-10-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcq", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcqresponse",
            name="mode_type",
            field=models.CharField(
                choices=[("practice", "训练模式"), ("exam", "考试模式")],
                default="practice",
                help_text="训练模式或考试模式",
                max_length=20,
                verbose_name="模式类型",
            ),
        ),
    ]
