# Generated by Django 4.2.1 on 2025-10-24 02:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_mediaasset_bitrate_mediaasset_sample_rate"),
        ("mcq", "0002_mcqresponse_mode_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mcqchoice",
            options={
                "ordering": ["label"],
                "verbose_name": "选择题选项",
                "verbose_name_plural": "选择题选项",
            },
        ),
        migrations.AlterField(
            model_name="mcqchoice",
            name="content",
            field=models.TextField(max_length=1000, verbose_name="选项内容"),
        ),
        migrations.AlterField(
            model_name="mcqchoice",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="是否正确答案"),
        ),
        migrations.AlterField(
            model_name="mcqchoice",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="自动生成A、B、C、D，也可手动指定",
                max_length=1,
                validators=[
                    django.core.validators.RegexValidator(
                        message="选项标签必须是A、B、C、D中的一个", regex="[ABCD]"
                    )
                ],
                verbose_name="选项标签",
            ),
        ),
        migrations.AlterField(
            model_name="mcqquestion",
            name="audio_asset",
            field=models.ForeignKey(
                blank=True,
                db_column="audio_id",
                help_text="单独题目的音频（如果有关联材料，可留空使用材料音频）",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mcq_questions",
                to="media.mediaasset",
                verbose_name="题目音频资源",
            ),
        ),
        migrations.AlterField(
            model_name="mcqquestion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="mcqquestion",
            name="text_stem",
            field=models.TextField(blank=True, null=True, verbose_name="题干文本"),
        ),
        migrations.CreateModel(
            name="McqMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="例如：机场天气广播、空中交通对话等",
                        max_length=200,
                        verbose_name="材料标题",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="材料的背景说明或场景描述",
                        max_length=1000,
                        null=True,
                        verbose_name="材料描述",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="听力材料的文字稿（可选）",
                        null=True,
                        verbose_name="材料文本内容",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "简单"),
                            ("medium", "中等"),
                            ("hard", "困难"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="难度级别",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="数字越小越靠前", verbose_name="显示顺序"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "audio_asset",
                    models.ForeignKey(
                        db_column="audio_id",
                        help_text="听力材料的音频文件",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mcq_materials",
                        to="media.mediaasset",
                        verbose_name="关联音频资源",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCQ听力材料",
                "verbose_name_plural": "MCQ听力材料",
                "db_table": "mcq_materials",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mcqquestion",
            name="material",
            field=models.ForeignKey(
                blank=True,
                help_text="如果题目属于某个材料，选择对应的材料",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="mcq.mcqmaterial",
                verbose_name="关联听力材料",
            ),
        ),
    ]
