# Generated by Django 4.2.1 on 2025-10-24 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mcq", "0003_alter_mcqchoice_options_alter_mcqchoice_content_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mcqmaterial",
            options={
                "ordering": ["display_order", "-created_at"],
                "verbose_name": "听力材料",
                "verbose_name_plural": "听力材料",
            },
        ),
    ]
