# Generated by Django 4.2.1 on 2025-10-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcq", "0004_alter_mcqmaterial_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcqmaterial",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="留空则自动使用音频文件名，例如：机场天气广播、空中交通对话等",
                max_length=200,
                verbose_name="材料标题",
            ),
        ),
    ]
