# Generated by Django 4.2.1 on 2025-10-24 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_mediaasset_bitrate_mediaasset_sample_rate"),
        ("mcq", "0005_alter_mcqmaterial_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcqmaterial",
            name="audio_asset",
            field=models.ForeignKey(
                blank=True,
                db_column="audio_id",
                help_text="听力材料的音频文件",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mcq_materials",
                to="media.mediaasset",
                verbose_name="关联音频资源",
            ),
        ),
        migrations.AlterField(
            model_name="mcqquestion",
            name="audio_asset",
            field=models.ForeignKey(
                blank=True,
                db_column="audio_id",
                help_text="单独题目的音频（如果有关联材料，可留空使用材料音频）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mcq_questions",
                to="media.mediaasset",
                verbose_name="题目音频资源",
            ),
        ),
    ]
