# Generated by Django 4.2.1 on 2025-10-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0005_alter_exammodule_exam_paper"),
        ("mcq", "0006_alter_mcqmaterial_audio_asset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcqresponse",
            name="module",
            field=models.ManyToManyField(
                db_column="module_id",
                related_name="module_mcq_response",
                to="exam.exammodule",
            ),
        ),
    ]
