# Generated by Django 4.2.1 on 2025-10-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0005_alter_exammodule_exam_paper"),
        ("mcq", "0007_mcqresponse_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcqmaterial",
            name="exam_module",
            field=models.ManyToManyField(
                blank=True,
                db_column="module_id",
                related_name="mcq_materials",
                to="exam.exammodule",
                verbose_name="关联考试模块",
            ),
        ),
        migrations.AlterField(
            model_name="mcqquestion",
            name="exam_module",
            field=models.ManyToManyField(
                blank=True,
                help_text="选择该题目所属的试题模块",
                related_name="mcq_questions",
                to="exam.exammodule",
                verbose_name="关联考试模块",
            ),
        ),
    ]
