# Generated by Django 4.2.1 on 2025-10-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mcq", "0008_mcqmaterial_exam_module_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mcqquestion",
            name="exam_module",
        ),
    ]
