# Generated by Django 4.2.1 on 2025-10-22 06:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="角色名称"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="描述"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="角色编码"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "激活"), (0, "禁用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="WxUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openid",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="微信用户唯一标识"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="用户名",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="电话"
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="头像URL"
                    ),
                ),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女"), (0, "未知")],
                        null=True,
                        verbose_name="性别",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="出生日期"),
                ),
                ("level", models.IntegerField(null=True, verbose_name="等级/级别")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="所在地"
                    ),
                ),
                (
                    "join_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="加入日期"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "正常"), (0, "禁用")],
                        default=1,
                        verbose_name="用户状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "roles",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.role"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=255, verbose_name="密码")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="邮箱",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="电话"
                    ),
                ),
                (
                    "avatar",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="头像URL"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "正常"), (0, "禁用")],
                        default=1,
                        verbose_name="用户状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "roles",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.role"
                    ),
                ),
            ],
            options={
                "verbose_name": "后台管理用户",
                "verbose_name_plural": "后台管理用户",
                "db_table": "admin_users",
            },
        ),
    ]
