# Generated by Django 4.2.1 on 2025-10-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminUser",
        ),
    ]
