# Generated by Django 4.2.1 on 2025-10-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_delete_adminuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wxuser",
            name="roles",
        ),
        migrations.AddField(
            model_name="wxuser",
            name="last_login",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
