# Generated by Django 4.2.1 on 2025-10-23 01:00

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_wxuser_roles_wxuser_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wxuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="支持jpg, jpeg, png, gif格式",
                null=True,
                upload_to=account.models.user_avatar_upload_path,
                verbose_name="用户头像",
            ),
        ),
        migrations.AlterField(
            model_name="wxuser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最后登录时间"
            ),
        ),
    ]
