# Generated by Django 4.2.1 on 2025-10-23 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_wxuser_avatar_alter_wxuser_last_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLearningProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mcq_total", models.IntegerField(default=0, verbose_name="MCQ总题数")),
                (
                    "mcq_completed",
                    models.IntegerField(default=0, verbose_name="MCQ已完成题数"),
                ),
                (
                    "mcq_correct",
                    models.IntegerField(default=0, verbose_name="MCQ正确题数"),
                ),
                (
                    "mcq_practice_count",
                    models.IntegerField(default=0, verbose_name="MCQ训练次数"),
                ),
                (
                    "mcq_exam_count",
                    models.IntegerField(default=0, verbose_name="MCQ考试次数"),
                ),
                ("lsa_total", models.IntegerField(default=0, verbose_name="LSA总题数")),
                (
                    "lsa_completed",
                    models.IntegerField(default=0, verbose_name="LSA已完成题数"),
                ),
                (
                    "lsa_practice_count",
                    models.IntegerField(default=0, verbose_name="LSA训练次数"),
                ),
                (
                    "lsa_exam_count",
                    models.IntegerField(default=0, verbose_name="LSA考试次数"),
                ),
                (
                    "story_total",
                    models.IntegerField(default=0, verbose_name="Story总题数"),
                ),
                (
                    "story_completed",
                    models.IntegerField(default=0, verbose_name="Story已完成题数"),
                ),
                (
                    "story_avg_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Story平均分",
                    ),
                ),
                (
                    "story_practice_count",
                    models.IntegerField(default=0, verbose_name="Story训练次数"),
                ),
                (
                    "story_exam_count",
                    models.IntegerField(default=0, verbose_name="Story考试次数"),
                ),
                ("opi_total", models.IntegerField(default=0, verbose_name="OPI总题数")),
                (
                    "opi_completed",
                    models.IntegerField(default=0, verbose_name="OPI已完成题数"),
                ),
                (
                    "opi_avg_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="OPI平均分",
                    ),
                ),
                (
                    "opi_practice_count",
                    models.IntegerField(default=0, verbose_name="OPI训练次数"),
                ),
                (
                    "opi_exam_count",
                    models.IntegerField(default=0, verbose_name="OPI考试次数"),
                ),
                (
                    "atc_total",
                    models.IntegerField(default=0, verbose_name="ATC总轮次数"),
                ),
                (
                    "atc_completed",
                    models.IntegerField(default=0, verbose_name="ATC已完成轮次数"),
                ),
                (
                    "atc_avg_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="ATC平均分",
                    ),
                ),
                (
                    "atc_practice_count",
                    models.IntegerField(default=0, verbose_name="ATC训练次数"),
                ),
                (
                    "atc_exam_count",
                    models.IntegerField(default=0, verbose_name="ATC考试次数"),
                ),
                (
                    "total_study_time",
                    models.IntegerField(default=0, verbose_name="总学习时长(分钟)"),
                ),
                (
                    "total_practice_count",
                    models.IntegerField(default=0, verbose_name="总训练次数"),
                ),
                (
                    "total_exam_count",
                    models.IntegerField(default=0, verbose_name="总考试次数"),
                ),
                (
                    "continuous_days",
                    models.IntegerField(default=0, verbose_name="连续学习天数"),
                ),
                (
                    "last_study_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="最后学习日期"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_progress",
                        to="account.wxuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户学习进度",
                "verbose_name_plural": "用户学习进度",
                "db_table": "user_learning_progress",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="userlearningprogress",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_user_progress"
            ),
        ),
    ]
