# Generated by Django 4.2.1 on 2025-10-22 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvVocabTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name_zh", models.CharField(max_length=200)),
                ("name_en", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=5000, null=True),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "航空词汇主题",
                "verbose_name_plural": "航空词汇主题",
                "db_table": "av_vocab_topics",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AvVocab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headword", models.CharField(max_length=200)),
                ("lemma", models.CharField(blank=True, max_length=200, null=True)),
                ("pos", models.CharField(blank=True, max_length=50, null=True)),
                ("ipa", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "definition_zh",
                    models.TextField(blank=True, max_length=5000, null=True),
                ),
                (
                    "example_en",
                    models.TextField(blank=True, max_length=2000, null=True),
                ),
                (
                    "example_zh",
                    models.TextField(blank=True, max_length=2000, null=True),
                ),
                (
                    "cefr_level",
                    models.CharField(
                        blank=True,
                        choices=[("A", "初级"), ("B", "中级"), ("C", "高级")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audio_asset",
                    models.ForeignKey(
                        blank=True,
                        db_column="audio_asset_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vocabs",
                        to="media.mediaasset",
                        verbose_name="发音音频",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        db_column="topic_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vocabs",
                        to="vocab.avvocabtopic",
                        verbose_name="所属主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "航空词汇",
                "verbose_name_plural": "航空词汇",
                "db_table": "av_vocabs",
            },
        ),
    ]
