# Generated by Django 4.2.1 on 2025-10-23 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("term", "0001_initial"),
        ("account", "0005_userlearningprogress_and_more"),
        ("vocab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTermLearning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "study_count",
                    models.IntegerField(default=1, verbose_name="学习次数"),
                ),
                (
                    "mastery_level",
                    models.IntegerField(
                        choices=[
                            (0, "未掌握"),
                            (1, "初步了解"),
                            (2, "基本掌握"),
                            (3, "熟练掌握"),
                            (4, "完全掌握"),
                        ],
                        default=1,
                        verbose_name="掌握程度",
                    ),
                ),
                (
                    "is_favorited",
                    models.BooleanField(default=False, verbose_name="是否收藏"),
                ),
                (
                    "is_mastered",
                    models.BooleanField(default=False, verbose_name="是否已掌握"),
                ),
                (
                    "first_learned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="首次学习时间"
                    ),
                ),
                (
                    "last_learned_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后学习时间"),
                ),
                (
                    "next_review_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次复习时间"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="学习备注"
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_learnings",
                        to="term.avterm",
                        verbose_name="术语",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="term_learnings",
                        to="account.wxuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户术语学习记录",
                "verbose_name_plural": "用户术语学习记录",
                "db_table": "user_term_learning",
                "ordering": ["-last_learned_at"],
            },
        ),
        migrations.CreateModel(
            name="UserVocabLearning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "study_count",
                    models.IntegerField(default=1, verbose_name="学习次数"),
                ),
                (
                    "mastery_level",
                    models.IntegerField(
                        choices=[
                            (0, "未掌握"),
                            (1, "初步了解"),
                            (2, "基本掌握"),
                            (3, "熟练掌握"),
                            (4, "完全掌握"),
                        ],
                        default=1,
                        verbose_name="掌握程度",
                    ),
                ),
                (
                    "is_favorited",
                    models.BooleanField(default=False, verbose_name="是否收藏"),
                ),
                (
                    "is_mastered",
                    models.BooleanField(default=False, verbose_name="是否已掌握"),
                ),
                (
                    "first_learned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="首次学习时间"
                    ),
                ),
                (
                    "last_learned_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后学习时间"),
                ),
                (
                    "next_review_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次复习时间"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="学习备注"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocab_learnings",
                        to="account.wxuser",
                        verbose_name="用户",
                    ),
                ),
                (
                    "vocab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_learnings",
                        to="vocab.avvocab",
                        verbose_name="词汇",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户词汇学习记录",
                "verbose_name_plural": "用户词汇学习记录",
                "db_table": "user_vocab_learning",
                "ordering": ["-last_learned_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_learned_at"],
                        name="user_vocab__user_id_b0c3d3_idx",
                    ),
                    models.Index(
                        fields=["user", "is_favorited"],
                        name="user_vocab__user_id_3edc3c_idx",
                    ),
                    models.Index(
                        fields=["user", "is_mastered"],
                        name="user_vocab__user_id_f41baf_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="uservocablearning",
            constraint=models.UniqueConstraint(
                fields=("user", "vocab"), name="unique_user_vocab_learning"
            ),
        ),
        migrations.AddIndex(
            model_name="usertermlearning",
            index=models.Index(
                fields=["user", "-last_learned_at"],
                name="user_term_l_user_id_0bbaf3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usertermlearning",
            index=models.Index(
                fields=["user", "is_favorited"], name="user_term_l_user_id_c2ef38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usertermlearning",
            index=models.Index(
                fields=["user", "is_mastered"], name="user_term_l_user_id_8fcaeb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usertermlearning",
            constraint=models.UniqueConstraint(
                fields=("user", "term"), name="unique_user_term_learning"
            ),
        ),
    ]
