# Generated by Django 4.2.1 on 2025-10-28 02:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exam", "0005_alter_exammodule_exam_paper"),
        ("account", "0005_userlearningprogress_and_more"),
        ("media", "0003_mediaasset_bitrate_mediaasset_sample_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="LsaDialog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("display_order", models.BigIntegerField(default=0, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audio_asset",
                    models.ForeignKey(
                        blank=True,
                        db_column="audio_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dialogs",
                        to="media.mediaasset",
                        verbose_name="对话音频资源",
                    ),
                ),
                (
                    "exam_module",
                    models.ManyToManyField(
                        blank=True,
                        db_column="module_id",
                        related_name="module_lsa",
                        to="exam.exammodule",
                        verbose_name="关联考试模块",
                    ),
                ),
            ],
            options={
                "verbose_name": "听力简单对话",
                "verbose_name_plural": "听力简单对话",
                "db_table": "lsa_dialogs",
            },
        ),
        migrations.CreateModel(
            name="LsaQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.CharField(
                        help_text="输入题目内容",
                        max_length=2000,
                        verbose_name="题目文本",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        blank=True,
                        help_text="数字越小越靠前",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="显示顺序",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="取消激活后该题目将不会显示",
                        verbose_name="是否激活",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dialog",
                    models.ManyToManyField(
                        blank=True,
                        db_column="dialog_id",
                        help_text="可选择该问题所属的对话（可多选）",
                        related_name="lsa_questions",
                        to="lsa.lsadialog",
                        verbose_name="关联对话",
                    ),
                ),
                (
                    "question_audio",
                    models.ForeignKey(
                        blank=True,
                        db_column="question_audio_id",
                        help_text="上传问题音频文件",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lsa_questions_audio",
                        to="media.mediaasset",
                        verbose_name="问题音频",
                    ),
                ),
            ],
            options={
                "verbose_name": "听力简单问题",
                "verbose_name_plural": "听力简单问题",
                "db_table": "lsa_questions",
            },
        ),
        migrations.CreateModel(
            name="LsaResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode_type",
                    models.CharField(
                        choices=[("practice", "训练模式"), ("exam", "考试模式")],
                        default="practice",
                        help_text="训练模式或考试模式",
                        max_length=20,
                        verbose_name="模式类型",
                    ),
                ),
                ("is_timeout", models.BooleanField(default=False)),
                (
                    "answered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer_audio",
                    models.ForeignKey(
                        blank=True,
                        db_column="answer_audio_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lsa_responses_audio",
                        to="media.mediaasset",
                        verbose_name="回答音频资源",
                    ),
                ),
                (
                    "modules",
                    models.ManyToManyField(
                        db_column="module_id",
                        related_name="module_lsa_response",
                        to="exam.exammodule",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lsa_responses",
                        to="lsa.lsaquestion",
                        verbose_name="关联题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.wxuser",
                        verbose_name="回答人",
                    ),
                ),
            ],
            options={
                "verbose_name": "听力简单作答",
                "verbose_name_plural": "听力简单作答",
                "db_table": "lsa_responses",
            },
        ),
        migrations.AddField(
            model_name="lsadialog",
            name="related_questions",
            field=models.ManyToManyField(
                blank=True,
                help_text="可选择关联的听力简答问题（除了对话自己的问题外，还可以引用其他问题）",
                related_name="related_dialogs",
                to="lsa.lsaquestion",
                verbose_name="关联听力简答问题",
            ),
        ),
    ]
