# Generated by Django 4.2.1 on 2025-10-22 06:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        ("account", "0001_initial"),
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LsaDialog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("display_order", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audio_asset",
                    models.ForeignKey(
                        blank=True,
                        db_column="audio_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dialogs",
                        to="media.mediaasset",
                        verbose_name="对话音频资源",
                    ),
                ),
                (
                    "exam_module",
                    models.ManyToManyField(
                        db_column="module_id",
                        related_name="module_lsa",
                        to="exam.exammodule",
                        verbose_name="关联考试模块",
                    ),
                ),
            ],
            options={
                "verbose_name": "听力理解对话",
                "verbose_name_plural": "听力理解对话",
                "db_table": "lsa_dialogs",
            },
        ),
        migrations.CreateModel(
            name="LsaQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_type", models.CharField(max_length=50)),
                ("question_text", models.CharField(max_length=2000)),
                ("option_a", models.CharField(blank=True, max_length=500, null=True)),
                ("option_b", models.CharField(blank=True, max_length=500, null=True)),
                ("option_c", models.CharField(blank=True, max_length=500, null=True)),
                ("option_d", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "correct_answer",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "answer_explanation",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dialog",
                    models.ForeignKey(
                        db_column="dialog_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="lsa.lsadialog",
                        verbose_name="关联对话",
                    ),
                ),
            ],
            options={
                "verbose_name": "听力理解问题",
                "verbose_name_plural": "听力理解问题",
                "db_table": "lsa_questions",
            },
        ),
        migrations.CreateModel(
            name="LsaResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_timeout", models.BooleanField(default=False)),
                (
                    "answered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer_audio",
                    models.ForeignKey(
                        blank=True,
                        db_column="answer_audio_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="media.mediaasset",
                        verbose_name="回答音频资源",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="lsa.lsaquestion",
                        verbose_name="关联题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.wxuser",
                        verbose_name="回答人",
                    ),
                ),
            ],
            options={
                "verbose_name": "口语作答",
                "verbose_name_plural": "口语作答",
                "db_table": "lsa_responses",
            },
        ),
    ]
