# Generated by Django 4.2.1 on 2025-10-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lsa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lsaquestion",
            name="dialog",
            field=models.ManyToManyField(
                blank=True,
                db_column="dialog_id",
                help_text="可选择该问题所属的对话（可多选）",
                to="lsa.lsadialog",
                verbose_name="关联对话",
            ),
        ),
    ]
