# Generated by Django 4.2.1 on 2025-10-28 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lsa", "0003_alter_lsaquestion_dialog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lsadialog",
            name="related_questions",
        ),
    ]
