# Generated by Django 4.2.1 on 2025-10-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lsa", "0004_remove_lsadialog_related_questions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lsadialog",
            options={
                "verbose_name": "听力简答对话",
                "verbose_name_plural": "听力简答对话",
            },
        ),
        migrations.AlterModelOptions(
            name="lsaquestion",
            options={
                "verbose_name": "听力简答问题",
                "verbose_name_plural": "听力简答问题",
            },
        ),
    ]
