# Generated by Django 4.2.1 on 2025-10-22 06:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        ("account", "0001_initial"),
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetellItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audio_asset",
                    models.ForeignKey(
                        db_column="audio_asset_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retell_items",
                        to="media.mediaasset",
                        verbose_name="音频资源",
                    ),
                ),
                (
                    "exam_modules",
                    models.ManyToManyField(
                        related_name="retell_items",
                        to="exam.exammodule",
                        verbose_name="关联考试模块",
                    ),
                ),
            ],
            options={
                "verbose_name": "复述题目",
                "verbose_name_plural": "复述题目",
                "db_table": "retell_items",
            },
        ),
        migrations.CreateModel(
            name="RetellResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_timeout", models.BooleanField(default=False)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer_audio",
                    models.ForeignKey(
                        blank=True,
                        db_column="answer_audio_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retell_responses",
                        to="media.mediaasset",
                        verbose_name="回答音频资源",
                    ),
                ),
                (
                    "retell_item",
                    models.ForeignKey(
                        db_column="item_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="story.retellitem",
                        verbose_name="关联复述题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.wxuser",
                        verbose_name="回答人",
                    ),
                ),
            ],
            options={
                "verbose_name": "复述回答",
                "verbose_name_plural": "复述回答",
                "db_table": "retell_responses",
            },
        ),
    ]
