# Generated by Django 4.2.1 on 2025-10-22 06:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        ("account", "0001_initial"),
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpiQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "QOrder",
                    models.IntegerField(
                        db_column="q_order",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="问题顺序必须大于0"
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prompt_audio",
                    models.ForeignKey(
                        db_column="prompt_audio_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opi_questions",
                        to="media.mediaasset",
                        verbose_name="提问音频",
                    ),
                ),
            ],
            options={
                "verbose_name": "OPI问题",
                "verbose_name_plural": "OPI问题",
                "db_table": "opi_questions",
            },
        ),
        migrations.CreateModel(
            name="OpiTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(db_column="t_order")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam_module",
                    models.ManyToManyField(
                        blank=True,
                        db_column="module_id",
                        related_name="opi_topic",
                        to="exam.exammodule",
                        verbose_name="所属模块",
                    ),
                ),
            ],
            options={
                "verbose_name": "OPI话题",
                "verbose_name_plural": "OPI话题",
                "db_table": "opi_topics",
            },
        ),
        migrations.CreateModel(
            name="OpiResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("is_timeout", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer_audio",
                    models.ForeignKey(
                        blank=True,
                        db_column="answer_audio_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opi_responses",
                        to="media.mediaasset",
                        verbose_name="回答音频",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="opi.opiquestion",
                        verbose_name="关联问题",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.wxuser",
                        verbose_name="回答人",
                    ),
                ),
            ],
            options={
                "verbose_name": "OPI回答",
                "verbose_name_plural": "OPI回答",
                "db_table": "opi_responses",
            },
        ),
        migrations.AddField(
            model_name="opiquestion",
            name="topic",
            field=models.ForeignKey(
                db_column="topic_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="opi.opitopic",
                verbose_name="关联话题",
            ),
        ),
        migrations.AddConstraint(
            model_name="opiresponse",
            constraint=models.UniqueConstraint(
                fields=("question",), name="uk_question_only"
            ),
        ),
    ]
