# Generated by Django 4.2.1 on 2025-10-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0005_alter_exammodule_exam_paper"),
        ("opi", "0002_opiresponse_mode_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="opiresponse",
            name="modules",
            field=models.ManyToManyField(
                db_column="module_id",
                related_name="module_opi_response",
                to="exam.exammodule",
            ),
        ),
    ]
