# Generated by Django 4.2.1 on 2025-10-22 06:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        ("account", "0001_initial"),
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icao",
                    models.CharField(
                        max_length=8,
                        unique=True,
                        verbose_name="国际民航组织（ICAO）四字代码",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="机场名称")),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="机场所在城市",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="机场所在国家",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="时区"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "机场",
                "verbose_name_plural": "机场",
                "db_table": "airports",
                "ordering": ["icao"],
            },
        ),
        migrations.CreateModel(
            name="AtcScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="场景标题")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, null=True, verbose_name="场景描述"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scenarios",
                        to="atc.airport",
                        verbose_name="机场",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atc_scenarios",
                        to="exam.exammodule",
                        verbose_name="关联模块",
                    ),
                ),
            ],
            options={
                "verbose_name": "ATC场景",
                "verbose_name_plural": "ATC场景",
                "db_table": "atc_scenarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AtcTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turn_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="轮次序号必须大于0"
                            )
                        ],
                        verbose_name="轮次序号",
                    ),
                ),
                (
                    "speaker_type",
                    models.CharField(
                        choices=[("pilot", "飞行员"), ("controller", "管制员")],
                        max_length=20,
                        verbose_name="说话者类型",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "audio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns_audio",
                        to="media.mediaasset",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="atc.atcscenario",
                        verbose_name="关联场景",
                    ),
                ),
            ],
            options={
                "verbose_name": "ATC轮次",
                "verbose_name_plural": "ATC轮次",
                "db_table": "atc_turns",
                "ordering": ["scenario", "turn_number"],
                "unique_together": {("scenario", "turn_number")},
            },
        ),
        migrations.CreateModel(
            name="AtcTurnResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_timeout", models.BooleanField(default=False)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.0"), message="得分不能为负数"
                            )
                        ],
                        verbose_name="得分",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "atc_turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="atc.atcturn",
                        verbose_name="关联轮次",
                    ),
                ),
                (
                    "audio_file_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="media.mediaasset",
                        verbose_name="音频文件路径",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atc_turn_responses",
                        to="account.wxuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "ATC轮次回答",
                "verbose_name_plural": "ATC轮次回答",
                "db_table": "atc_turn_responses",
                "ordering": ["-created_at"],
            },
        ),
    ]
