# Generated by Django 4.2.1 on 2025-10-28 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0005_alter_exammodule_exam_paper"),
        ("atc", "0003_atcturnresponse_modules"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atcturn",
            options={
                "ordering": ["turn_number", "-created_at"],
                "verbose_name": "ATC轮次",
                "verbose_name_plural": "ATC轮次",
            },
        ),
        migrations.AlterUniqueTogether(
            name="atcturn",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="atcscenario",
            name="module",
        ),
        migrations.AlterField(
            model_name="atcturn",
            name="turn_number",
            field=models.IntegerField(
                auto_created=True,
                default=1,
                editable=False,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="轮次序号必须大于0"
                    )
                ],
                verbose_name="轮次序号",
            ),
        ),
        migrations.AddField(
            model_name="atcscenario",
            name="module",
            field=models.ManyToManyField(
                related_name="atc_scenarios",
                to="exam.exammodule",
                verbose_name="关联模块",
            ),
        ),
        migrations.RemoveField(
            model_name="atcturn",
            name="scenario",
        ),
        migrations.AddField(
            model_name="atcturn",
            name="scenario",
            field=models.ManyToManyField(
                related_name="atc_turns", to="atc.atcscenario", verbose_name="关联场景"
            ),
        ),
    ]
