# Generated by Django 4.2.1 on 2025-10-28 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atc", "0004_alter_atcturn_options_alter_atcturn_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atcturn",
            name="turn_number",
            field=models.IntegerField(
                default=1,
                help_text="指定该轮次在对话中的顺序（第1轮、第2轮等）",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="轮次序号必须大于0"
                    )
                ],
                verbose_name="轮次序号",
            ),
        ),
    ]
