# Generated by Django 4.2.1 on 2025-10-28 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("atc", "0005_alter_atcturn_turn_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atcturn",
            options={
                "ordering": ["scenario", "turn_number"],
                "verbose_name": "ATC轮次",
                "verbose_name_plural": "ATC轮次",
            },
        ),
        migrations.AlterUniqueTogether(
            name="atcturn",
            unique_together={("scenario", "turn_number")},
        ),
        migrations.RemoveField(
            model_name="atcturn",
            name="scenario",
        ),
        migrations.AddField(
            model_name="atcturn",
            name="scenario",
            field=models.ForeignKey(
                default="",
                help_text="选择该轮次所属的场景",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atc_turns",
                to="atc.atcscenario",
                verbose_name="关联场景",
            ),
            preserve_default=False,
        ),
    ]
