# Generated by Django 4.2.1 on 2025-10-28 07:12

from django.db import migrations, models


def prepare_for_json_conversion(apps, schema_editor):
    """
    准备将TextField转换为JSONField
    将所有现有的文本描述转换为包含该文本的JSON对象
    """
    AtcScenario = apps.get_model('atc', 'AtcScenario')
    
    for scenario in AtcScenario.objects.all():
        if scenario.description:
            # 将文本内容包装为JSON格式的字符串
            # 转换前：scenario.description = "这是一个紧急情况"
            # 转换后：scenario.description = '{"description": "这是一个紧急情况"}'
            import json
            try:
                # 检查是否已经是有效的JSON
                json.loads(scenario.description)
                # 如果已经是JSON，不做修改
            except (json.JSONDecodeError, TypeError, ValueError):
                # 如果不是JSON，将文本包装为JSON对象
                text_content = str(scenario.description)
                scenario.description = json.dumps({"description": text_content}, ensure_ascii=False)
                scenario.save(update_fields=['description'])


def reverse_json_conversion(apps, schema_editor):
    """
    回滚操作：将JSON转换回文本
    """
    AtcScenario = apps.get_model('atc', 'AtcScenario')
    import json
    
    for scenario in AtcScenario.objects.all():
        if scenario.description:
            try:
                data = json.loads(scenario.description) if isinstance(scenario.description, str) else scenario.description
                if isinstance(data, dict) and 'description' in data:
                    scenario.description = data['description']
                    scenario.save(update_fields=['description'])
            except:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ("atc", "0006_alter_atcturn_options_alter_atcturn_unique_together_and_more"),
    ]

    operations = [
        # 步骤1：数据转换 - 将文本转换为JSON字符串格式
        migrations.RunPython(prepare_for_json_conversion, reverse_json_conversion),
        
        # 步骤2：修改字段类型为JSONField
        migrations.AlterField(
            model_name="atcscenario",
            name="description",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='JSON格式的场景描述，例如：{"situation": "紧急情况", "weather": "晴天", "traffic": "繁忙"}',
                null=True,
                verbose_name="场景描述",
            ),
        ),
    ]
