"""
Django settings for icao4Backend project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1sm*14nyr(ks@7a$1#akbb*4lpjm2_!x87&u(0v7r-%htehk3a"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Jazzmin 必须放在第一位
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    'common',  # 公共模块
    'account',
    'atc',
    'banner',
    'exam',
    'lsa',
    'mcq',
    'media',
    'opi',
    'story',
    'term',
    'vocab'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "icao4Backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "icao4Backend.wsgi.application"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # 格式: redis://[密码@]主机:端口/数据库编号
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # 可选：如果 Redis 需要密码认证
            # "PASSWORD": "your_redis_password",
            # 可选：连接池设置
            # "CONNECTION_POOL_KWARGS": {"max_connections": 100},
        },
        # 可选：设置默认超时时间（秒）。如果未设置，则永久缓存。
        "TIMEOUT": 300,  # 缓存 5 分钟
        # 可选：设置 key 的前缀，以避免与其他应用冲突
        "KEY_PREFIX": "icao4_django_cache",
    }
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"  # 中文简体

TIME_ZONE = "Asia/Shanghai"  # 中国时区

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 开发环境下的静态文件目录
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (用户上传的文件)
MEDIA_URL = '/upload/'
MEDIA_ROOT = BASE_DIR / 'upload'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ==================== Jazzmin 配置 ====================

JAZZMIN_SETTINGS = {
    # 网站标题
    "site_title": "ICAO4 管理系统",
    
    # 网站页眉标题
    "site_header": "ICAO4 航空英语考试系统",
    
    # 网站品牌
    "site_brand": "ICAO4 后台管理",
    
    # Logo
    "site_logo": "logo.png",  # 放在 static 目录下
    
    # 登录页Logo
    "login_logo": "logo.png",
    
    # Logo 类
    "site_logo_classes": "img-circle",
    
    # 网站图标
    "site_icon": "logo.png",
    
    # 欢迎标语
    "welcome_sign": "欢迎使用 ICAO4 航空英语考试系统",
    
    # 版权信息
    "copyright": "ICAO4 航空英语考试系统",
    
    # 搜索模型
    "search_model": ["auth.User", "auth.Group"],
    
    # 用户头像字段
    "user_avatar": None,
    
    ############
    # 顶部菜单 #
    ############
    
    # 是否显示顶部菜单
    "topmenu_links": [
        {"name": "首页", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "API文档", "url": "/api/", "new_window": True},
        {"model": "auth.User"},
        {"app": "media"},
    ],
    
    #############
    # 用户菜单 #
    #############
    
    # 是否显示用户菜单
    "usermenu_links": [
        {"model": "auth.user"}
    ],
    
    #############
    # 侧边栏 #
    #############
    
    # 是否显示侧边栏搜索
    "show_sidebar": True,
    
    # 是否显示导航搜索
    "navigation_expanded": True,
    
    # 隐藏的应用
    "hide_apps": [],
    
    # 隐藏的模型
    "hide_models": [],
    
    # 应用的图标（使用 Font Awesome 5）
    "icons": {
        # 认证相关
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        # 账户相关
        "account": "fas fa-user-circle",
        "account.WxUser": "fab fa-weixin",
        "account.Role": "fas fa-user-tag",
        "account.UserLearningProgress": "fas fa-chart-line",
        
        # 考试模块
        "exam": "fas fa-graduation-cap",
        "exam.ExamPaper": "fas fa-file-alt",
        "exam.ExamModule": "fas fa-puzzle-piece",
        
        # MCQ听力选择题
        "mcq": "fas fa-headphones",
        "mcq.McqMaterial": "fas fa-file-audio",
        "mcq.McqQuestion": "fas fa-question-circle",
        "mcq.McqChoice": "fas fa-list-ul",
        "mcq.McqResponse": "fas fa-check-circle",
        
        # LSA听力与理解
        "lsa": "fas fa-ear-listen",
        "lsa.LsaDialog": "fas fa-comment-dots",
        "lsa.LsaQuestion": "fas fa-question-circle",
        "lsa.LsaResponse": "fas fa-microphone",
        
        # 故事复述
        "story": "fas fa-book",
        "story.RetellItem": "fas fa-book-reader",
        "story.RetellResponse": "fas fa-comment",
        
        # OPI口语面试
        "opi": "fas fa-user-tie",
        "opi.OpiTopic": "fas fa-comments",
        "opi.OpiQuestion": "fas fa-question",
        "opi.OpiResponse": "fas fa-reply",
        
        # ATC空中交通管制
        "atc": "fas fa-broadcast-tower",
        "atc.Airport": "fas fa-plane-departure",
        "atc.AtcScenario": "fas fa-reply-all",
        "atc.AtcTurn": "fas fa-exchange-alt",
        "atc.AtcTurnResponse": "fas fa-reply-all",
        
        # 术语
        "term": "fas fa-book-open",
        "term.AvTermsTopic": "fas fa-tags",
        "term.AvTerm": "fas fa-language",
        
        # 词汇
        "vocab": "fas fa-spell-check",
        "vocab.AvVocabTopic": "fas fa-folder-open",
        "vocab.AvVocab": "fas fa-font",
        "vocab.UserVocabLearning": "fas fa-user-graduate",
        "vocab.UserTermLearning": "fas fa-user-graduate",
        
        # 轮播图
        "banner": "fas fa-image",
        "banner.Banner": "fas fa-images",
        "banner.BannerItem": "fas fa-photo-video",
        
        # 媒体资源
        "media": "fas fa-photo-video",
        "media.MediaAsset": "fas fa-file-audio",
        
        # 公共模块
        "common": "fas fa-cogs",
    },
    
    # 默认图标（对于没有指定图标的）
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    #################
    # 相关模态框 #
    #################
    
    # 使用模态框编辑相关对象
    "related_modal_active": False,
    
    #############
    # UI 调整 #
    #############
    
    # 自定义CSS
    "custom_css": None,
    
    # 自定义JS
    "custom_js": None,
    
    # 是否显示UI自定义器
    "show_ui_builder": False,
    
    ###############
    # 变更表单 #
    ###############
    
    # 单个模型页上的模态框
    "changeform_format": "horizontal_tabs",
    
    # 覆盖changeform的模板
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs"
    },
    
    # 语言选择器
    "language_chooser": False,
}

# Jazzmin UI 调整
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# ==================== JWT 配置 ====================
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),  # 访问令牌有效期7天
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),  # 刷新令牌有效期30天
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# ==================== DRF 配置 ====================
REST_FRAMEWORK = {
    # 认证
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'account.authentication.WxUserJWTAuthentication',
    ),
    # 权限
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # 渲染器 - 统一返回格式
    'DEFAULT_RENDERER_CLASSES': (
        'common.renderers.CustomJSONRenderer',
    ),
    # 分页
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # 异常处理 - 统一返回格式
    'EXCEPTION_HANDLER': 'common.exceptions.custom_exception_handler',
    # 日期时间格式
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
}

# ==================== CORS 配置 ====================
CORS_ALLOW_ALL_ORIGINS = True  # 开发环境，生产环境需要指定具体域名
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ==================== 微信小程序配置 ====================
WECHAT_MINI_PROGRAM = {
    'APP_ID': 'wxbd524017c02e9770',  # 请替换为你的微信小程序AppID
    'APP_SECRET': 'f62bffe2497f8002513dfe5235f25e20',  # 请替换为你的微信小程序AppSecret
    'LOGIN_URL': 'https://api.weixin.qq.com/sns/jscode2session',
}

# ==================== 日志配置 ====================
# 简化配置：只输出到控制台
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{levelname}] {asctime} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}


