# Generated by Django 4.2.1 on 2025-10-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("audio", "音频"),
                            ("image", "图像"),
                            ("video", "视频"),
                            ("doc", "文档"),
                        ],
                        max_length=10,
                        verbose_name="媒体类型",
                    ),
                ),
                ("uri", models.CharField(max_length=500)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "媒体资源",
                "verbose_name_plural": "媒体资源",
                "db_table": "media_assets",
            },
        ),
    ]
