# Generated by Django 4.2.1 on 2025-10-23 00:42

import django.core.validators
from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mediaasset",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "媒体资源",
                "verbose_name_plural": "媒体资源",
            },
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="文件描述"
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=media.models.media_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp3",
                            "wav",
                            "ogg",
                            "m4a",
                            "aac",
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "bmp",
                            "webp",
                            "svg",
                            "mp4",
                            "avi",
                            "mov",
                            "wmv",
                            "flv",
                            "webm",
                            "pdf",
                            "doc",
                            "docx",
                            "txt",
                            "ppt",
                            "pptx",
                            "xls",
                            "xlsx",
                        ]
                    )
                ],
                verbose_name="上传文件",
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="file_size",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="文件大小（字节）"
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="duration_ms",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="时长（毫秒）"
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="uri",
            field=models.CharField(
                blank=True,
                help_text="外部资源URL或相对路径",
                max_length=500,
                null=True,
                verbose_name="资源URI",
            ),
        ),
    ]
