# Generated by Django 4.2.1 on 2025-10-22 06:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="导播图组名称")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="导播图组描述",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序权重")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始显示时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束显示时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "导播图组",
                "verbose_name_plural": "导播图组",
                "db_table": "banners",
                "ordering": ["-sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="BannerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="图片标题"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="图片描述"
                    ),
                ),
                ("image_url", models.CharField(max_length=500, verbose_name="图片URL")),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="点击跳转链接",
                    ),
                ),
                (
                    "sort_weight",
                    models.IntegerField(default=0, verbose_name="排序权重"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "banner",
                    models.ForeignKey(
                        db_column="banner_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="banner.banner",
                        verbose_name="所属导播图组",
                    ),
                ),
            ],
            options={
                "verbose_name": "导播图项目",
                "verbose_name_plural": "导播图项目",
                "db_table": "banner_items",
                "ordering": ["-sort_weight", "created_at"],
            },
        ),
    ]
