# Generated by Django 4.2.1 on 2025-10-23 01:00

import banner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banner", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banneritem",
            name="image_url",
        ),
        migrations.AddField(
            model_name="banneritem",
            name="image",
            field=models.ImageField(
                default="",
                help_text="支持jpg, jpeg, png, gif格式",
                upload_to=banner.models.banner_image_upload_path,
                verbose_name="轮播图图片",
            ),
            preserve_default=False,
        ),
    ]
